name: Backend

on:
  push:

defaults:
  run:
    working-directory: ./app
jobs:
  build:
    name: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies # (assuming your project has dependencies)
        run: bun install # You can use npm/yarn/pnpm instead if you prefer
      - name: Run the formatter, the linter and assist actions
        run: bun run code
      - name: Run tests
        run: bun test
